on:
  push:
    tags:
      - '*'

name: Publish

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    steps:
      - uses: olegtarasov/get-tag@v2-release
        id: tag_name
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache NuGet packages
        uses: actions/cache/restore@v4
        with:
          key: dotnet-${{ runner.os }}-${{ runner.arch }}-nuget-${{ hashFiles('**/Directory.Packages.props') }}
          path: ~/.nuget/packages
      - name: Build and pack
        run: |
          $env:PackageVersion = "${{ steps.tag_name.outputs.tag }}"
          dotnet restore
          dotnet pack -c Release -o nupkg --no-restore
      - name: Publish
        run: |
          dotnet nuget push nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
